# Generated by Django 6.0.3 on 2026-03-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='hr_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewround',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='package',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='placementofficer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(max_length=20),
        ),
    ]
