# Generated by Django 6.0.3 on 2026-03-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0002_alter_college_code_alter_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='placementofficer',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
