# Generated by Django 6.0.2 on 2026-03-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0004_alter_placementofficer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='placementofficer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
