# Generated by Django 6.0.3 on 2026-06-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0007_alter_college_name_alter_college_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField(default=10)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_app.student')),
            ],
        ),
    ]
